import { DoctorProfile, Patient, ScanRecord, DashboardStats } from './types';

export const CURRENT_DOCTOR: DoctorProfile = {
  name: 'Dr. Arjun Patel',
  role: 'Pulmonologist & Chief Radiologist',
  department: 'Thoracic Imaging Dept.',
  hospital: 'Apex Medical Research Center',
  avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=256&auto=format&fit=crop',
  email: 'arjun.patel@hospital.org',
};

export const MOCK_STATS: DashboardStats = {
  totalScans: 128,
  normalScans: 96,
  abnormalScans: 24,
  avgModelAccuracy: 92,
};

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'pat-001',
    patientCode: 'PT-2025-0520',
    name: 'Rajesh Kumar',
    age: 45,
    gender: 'Male',
    lastScanDate: 'May 20, 2025',
    referringDoctor: 'Dr. Arjun Patel',
    historyNotes: 'Fever, persistent cough, shortness of breath for 5 days.',
    status: 'Abnormal',
    totalScans: 3,
  },
  {
    id: 'pat-002',
    patientCode: 'PT-2025-0519',
    name: 'Ananya Sharma',
    age: 32,
    gender: 'Female',
    lastScanDate: 'May 19, 2025',
    referringDoctor: 'Dr. Priya Mehta',
    historyNotes: 'Routine pre-employment screening chest X-ray.',
    status: 'Normal',
    totalScans: 1,
  },
  {
    id: 'pat-003',
    patientCode: 'PT-2025-0518',
    name: 'Mohit Verma',
    age: 60,
    gender: 'Male',
    lastScanDate: 'May 18, 2025',
    referringDoctor: 'Dr. Arjun Patel',
    historyNotes: 'History of heavy smoking, chronic night sweats.',
    status: 'Abnormal',
    totalScans: 4,
  },
  {
    id: 'pat-004',
    patientCode: 'PT-2025-0517',
    name: 'Sneha Iyer',
    age: 28,
    gender: 'Female',
    lastScanDate: 'May 17, 2025',
    referringDoctor: 'Dr. Rajesh Nair',
    historyNotes: 'Mild chest discomfort during deep respiration.',
    status: 'Normal',
    totalScans: 2,
  },
  {
    id: 'pat-005',
    patientCode: 'PT-2025-0516',
    name: 'Vikram Singh',
    age: 50,
    gender: 'Male',
    lastScanDate: 'May 16, 2025',
    referringDoctor: 'Dr. Arjun Patel',
    historyNotes: 'Shortness of breath, occupational dust exposure.',
    status: 'Abnormal',
    totalScans: 2,
  },
];

export const MOCK_SCANS: ScanRecord[] = [
  {
    id: 'scn-001',
    scanCode: 'SCN-2025-0520-001',
    patientId: 'pat-001',
    patientName: 'Rajesh Kumar',
    scanDate: 'May 20, 2025',
    imageUrl: '/scans/chest_xray_pneumonia.svg',
    heatmapUrl: '/scans/chest_xray_pneumonia.svg',
    primaryCondition: 'Pneumonia Detected',
    confidence: 87,
    severity: 'Moderate',
    affectedArea: 'Right Lower Lobe',
    analysisTimeSeconds: 2.34,
    findingsSummary: 'Infiltration observed in the right lower lung zone. Air-space consolidation consistent with bacterial pneumonia. Recommend clinical correlation and follow-up.',
    isNormal: false,
    marker3D: {
      x: 0.65,
      y: -0.95,
      z: 0.35,
      label: 'Abnormality Detected',
      regionName: 'Right Lower Lobe (Consolidation)',
    },
    diseaseBreakdown: [
      { disease: 'Pneumonia', probability: 87, category: 'primary' },
      { disease: 'Tuberculosis', probability: 8, category: 'low' },
      { disease: 'Fibrosis', probability: 3, category: 'low' },
      { disease: 'Other NIH Classes', probability: 2, category: 'low' },
    ],
  },
  {
    id: 'scn-002',
    scanCode: 'SCN-2025-0519-002',
    patientId: 'pat-002',
    patientName: 'Ananya Sharma',
    scanDate: 'May 19, 2025',
    imageUrl: '/scans/chest_xray_normal.svg',
    heatmapUrl: '/scans/chest_xray_normal.svg',
    primaryCondition: 'Normal Scan',
    confidence: 96,
    severity: 'Normal',
    affectedArea: 'None (Unremarkable)',
    analysisTimeSeconds: 1.82,
    findingsSummary: 'Clear lung fields with no focal consolidation, pleural effusion, or pneumothorax. Cardiac size is within normal limits.',
    isNormal: true,
    diseaseBreakdown: [
      { disease: 'Normal', probability: 96, category: 'primary' },
      { disease: 'Infiltration', probability: 2, category: 'low' },
      { disease: 'Atelectasis', probability: 1, category: 'low' },
      { disease: 'Other', probability: 1, category: 'low' },
    ],
  },
  {
    id: 'scn-003',
    scanCode: 'SCN-2025-0518-003',
    patientId: 'pat-003',
    patientName: 'Mohit Verma',
    scanDate: 'May 18, 2025',
    imageUrl: '/scans/chest_xray_pneumonia.svg',
    heatmapUrl: '/scans/chest_xray_pneumonia.svg',
    primaryCondition: 'Tuberculosis Suspicion',
    confidence: 78,
    severity: 'High',
    affectedArea: 'Apical Segment Left Upper Lobe',
    analysisTimeSeconds: 2.51,
    findingsSummary: 'Cavitary lesion and upper lobe opacity noted in left lung peak. Sputum culture & GeneXpert recommended immediately.',
    isNormal: false,
    marker3D: {
      x: -0.4,
      y: 0.55,
      z: 0.15,
      label: 'Abnormality Detected',
      regionName: 'Left Upper Lobe (Apical Cavity)',
    },
    diseaseBreakdown: [
      { disease: 'Tuberculosis', probability: 78, category: 'primary' },
      { disease: 'Pneumonia', probability: 14, category: 'secondary' },
      { disease: 'Fibrosis', probability: 5, category: 'low' },
      { disease: 'Other', probability: 3, category: 'low' },
    ],
  },
  {
    id: 'scn-004',
    scanCode: 'SCN-2025-0517-004',
    patientId: 'pat-004',
    patientName: 'Sneha Iyer',
    scanDate: 'May 17, 2025',
    imageUrl: '/scans/chest_xray_normal.svg',
    heatmapUrl: '/scans/chest_xray_normal.svg',
    primaryCondition: 'Normal Scan',
    confidence: 93,
    severity: 'Normal',
    affectedArea: 'None (Clear)',
    analysisTimeSeconds: 1.95,
    findingsSummary: 'Normal chest radiograph. Bronchovascular markings are symmetrical. Costophrenic angles are sharp.',
    isNormal: true,
    diseaseBreakdown: [
      { disease: 'Normal', probability: 93, category: 'primary' },
      { disease: 'Effusion', probability: 4, category: 'low' },
      { disease: 'Other', probability: 3, category: 'low' },
    ],
  },
  {
    id: 'scn-005',
    scanCode: 'SCN-2025-0516-005',
    patientId: 'pat-005',
    patientName: 'Vikram Singh',
    scanDate: 'May 16, 2025',
    imageUrl: '/scans/chest_xray_pneumonia.svg',
    heatmapUrl: '/scans/chest_xray_pneumonia.svg',
    primaryCondition: 'Pulmonary Fibrosis',
    confidence: 68,
    severity: 'Moderate',
    affectedArea: 'Bilateral Basal Zones',
    analysisTimeSeconds: 2.18,
    findingsSummary: 'Reticular opacity and honeycombing pattern observed in lower pulmonary regions bilaterally.',
    isNormal: false,
    marker3D: {
      x: 0.35,
      y: -0.5,
      z: 0.05,
      label: 'Abnormality Detected',
      regionName: 'Bilateral Basal Fibrosis',
    },
    diseaseBreakdown: [
      { disease: 'Fibrosis', probability: 68, category: 'primary' },
      { disease: 'Atelectasis', probability: 18, category: 'secondary' },
      { disease: 'Emphysema', probability: 10, category: 'low' },
      { disease: 'Other', probability: 4, category: 'low' },
    ],
  },
];
